version: '3'

services:

  backend:
    build: ./backend
    volumes:
      - ./backend/src/:/app/src
    ports:
      - 3000:3000
    links:
      - mysql
    depends_on:
      - mysql
    command: ["./wait-for-it.sh", "mysql:3306", "--", "npm", "run", "start:dev"]

  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=test
    command: mysqld --character-set-server=utf8
